- email: dev1@example.com
  name: Dev user 1
  allowed: true

- email: dev2@example.com
  name: Dev user 2
  allowed: true

- email: dev3@example.com
  name: Dev user 3
  allowed: false

- email: dev4@example.com
  name: Dev user 4
  allowed: true
  revoked: true
